projects:
  danzailb-staging:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: src/graphql
        region: us-east-1
        apiId: f475l4evvjghzgv3oihbpqwt6a
        maxDepth: 2
extensions:
  amplify:
    version: 3
